CREATE TABLE PHONGBAN (
    MAPHONGBAN VARCHAR2(10) PRIMARY KEY,
    TENPHONGBAN NVARCHAR2(100)
);

CREATE TABLE TAIKHOAN (
    USERID VARCHAR2(255) PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(500) NOT NULL, 
    EMAIL VARCHAR2(200),             
    HOTEN NVARCHAR2(100),
    MAPHONGBAN VARCHAR2(10),
    TRANGTHAI VARCHAR2(20) DEFAULT 'ACTIVE',
    GIOITINH NVARCHAR2(10),
    DIENTHOAI VARCHAR2(200),         
    CHUC_VU VARCHAR2(20) DEFAULT 'USER',
    TRUC_TUYEN NUMBER(1) DEFAULT 0,
    HOAT_DONG_CUOI DATE,
    AES_KEY_ENC VARCHAR2(1000), 
    AES_IV VARCHAR2(500),      
    CONSTRAINT FK_TK_PB FOREIGN KEY (MAPHONGBAN) REFERENCES PHONGBAN(MAPHONGBAN)
);

CREATE TABLE USER_KEYS (
    USERID VARCHAR2(255) PRIMARY KEY,
    PUBLIC_KEY CLOB,  
    PRIVATE_KEY CLOB,
    CONSTRAINT FK_KEYS_USER FOREIGN KEY (USERID) REFERENCES TAIKHOAN(USERID)
);

CREATE TABLE NHOMCHAT (
    MANHOM VARCHAR2(20) PRIMARY KEY,
    TENNHOM NVARCHAR2(100),
    LOAI_NHOM NUMBER(1) DEFAULT 0,
    NGAYTAO DATE DEFAULT SYSDATE,
    TAOBOI VARCHAR2(255),
    CONSTRAINT FK_NHOM_TK FOREIGN KEY (TAOBOI) REFERENCES TAIKHOAN(USERID)
);

CREATE TABLE THANHVIENNHOM (
    MANHOM VARCHAR2(20),
    USERID VARCHAR2(255),
    DUYET NUMBER(1) DEFAULT 1, 
    PRIMARY KEY (MANHOM, USERID),
    CONSTRAINT FK_TVN_NHOM FOREIGN KEY (MANHOM) REFERENCES NHOMCHAT(MANHOM),
    CONSTRAINT FK_TVN_TK FOREIGN KEY (USERID) REFERENCES TAIKHOAN(USERID)
);

CREATE TABLE TINNHAN (
    MATN VARCHAR2(50) PRIMARY KEY,
    MANHOM VARCHAR2(20),
    GUIBOI VARCHAR2(255),
    NOIDUNG NVARCHAR2(2000), 
    THOIGIAN DATE DEFAULT SYSDATE,
    CONSTRAINT FK_TN_NHOM FOREIGN KEY (MANHOM) REFERENCES NHOMCHAT(MANHOM),
    CONSTRAINT FK_TN_TK FOREIGN KEY (GUIBOI) REFERENCES TAIKHOAN(USERID)
);

CREATE TABLE THONGBAO (
    MATHONGBAO VARCHAR2(20) PRIMARY KEY,
    TIEUDE NVARCHAR2(200),
    NOIDUNG NVARCHAR2(1000),
    NGUOITAO VARCHAR2(255),
    NGAYTAO DATE,
    CONSTRAINT FK_TB_TK FOREIGN KEY (NGUOITAO) REFERENCES TAIKHOAN(USERID)
);

CREATE TABLE BANBE (
    USER_ID_1 VARCHAR2(255), 
    USER_ID_2 VARCHAR2(255), 
    TRANGTHAI NUMBER(1) DEFAULT 0, NGAYGUI DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BANBE PRIMARY KEY (USER_ID_1, USER_ID_2),
    CONSTRAINT FK_BB_U1 FOREIGN KEY (USER_ID_1) REFERENCES TAIKHOAN(USERID),
    CONSTRAINT FK_BB_U2 FOREIGN KEY (USER_ID_2) REFERENCES TAIKHOAN(USERID)
);

CREATE TABLE LOGIN_HISTORY (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERID VARCHAR2(255) NOT NULL, 
    LOGIN_TIME TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP, 
    IP_ADDRESS VARCHAR2(40),
    CONSTRAINT FK_LOG_TK FOREIGN KEY (USERID) REFERENCES TAIKHOAN(USERID)
);
ALTER TABLE LOGIN_HISTORY ADD (
    IP_ENCRYPTED RAW(2000), 
    SESSION_KEY_ENC RAW(2000)
);

-- =======================================================================================
-- MÃ HÓA AES 
-- =======================================================================================
CREATE OR REPLACE PACKAGE PKG_SECURITY AS
    FUNCTION Encrypt_AES(p_input IN VARCHAR2) RETURN VARCHAR2; 
    FUNCTION Decrypt_AES(p_input IN VARCHAR2) RETURN VARCHAR2;
END;
/
CREATE OR REPLACE PACKAGE BODY PKG_SECURITY AS
    v_key RAW(32) := UTL_RAW.CAST_TO_RAW('KhoaBiMat_Nhom8_1234567890123456'); 
    FUNCTION Encrypt_AES(p_input IN VARCHAR2) RETURN VARCHAR2 IS
        v_encrypted RAW(2000);
    BEGIN
        IF p_input IS NULL THEN RETURN NULL; END IF;
        v_encrypted := DBMS_CRYPTO.ENCRYPT(
            src => UTL_RAW.CAST_TO_RAW(p_input),
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_key
        );
        RETURN RAWTOHEX(v_encrypted);
    END;

    FUNCTION Decrypt_AES(p_input IN VARCHAR2) RETURN VARCHAR2 IS
        v_decrypted RAW(2000);
    BEGIN
        IF p_input IS NULL THEN RETURN NULL; END IF;
        v_decrypted := DBMS_CRYPTO.DECRYPT(
            src => HEXTORAW(p_input),
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_key
        );
        RETURN UTL_RAW.CAST_TO_VARCHAR2(v_decrypted);
    EXCEPTION WHEN OTHERS THEN RETURN NULL; END;
END;
/

-- =======================================================================================
--  MÃ HÓA RSA
-- =======================================================================================

-- Hàm Mã Hóa RSA
CREATE OR REPLACE FUNCTION MAHOARSA (
    P_TEXT     NVARCHAR2,
    KEYPUBLIC  VARCHAR2 DEFAULT 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCWCE4hrKayNHzD7iqY2eu/9O4pGe1nf601j93EVwzpbM/r4kp6WQA/u9riqt07DmvJdSAn5d17LXq7XQOnFsRJKPAcSHmaR5oC6SI2WDe7yF9Jzr/Qt4+nf4xDmTDu1Ekw9sMQfOyXN1HsqIsf6T5nX9OgNvK0oZl6RSvXWf90ewIDAQAB'
)
RETURN VARCHAR2
IS
BEGIN
    IF P_TEXT IS NULL THEN
        RETURN NULL;
    END IF;
    RETURN SYS.CRYPTO.RSA_ENCRYPT(
        TO_CHAR(P_TEXT),
        KEYPUBLIC
    );
END;
/

-- Hàm Giải Mã RSA
CREATE OR REPLACE FUNCTION GIAIMARSA (
    P_CIPHER   VARCHAR2,
    KEYPRIVATE VARCHAR2 DEFAULT 'MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJYITiGsprI0fMPuKpjZ67/07ikZ7Wd/rTWP3cRXDOlsz+viSnpZAD+72uKq3TsOa8l1ICfl3XstertdA6cWxEko8BxIeZpHmgLpIjZYN7vIX0nOv9C3j6d/jEOZMO7USTD2wxB87Jc3Ueyoix/pPmdf06A28rShmXpFK9dZ/3R7AgMBAAECgYAaOm92QZmOs9BP7FX0DLzC/Q2Zj9fJ7S8ZmwH47gLq18Pth8zfYKnDepLEZ3xvc5DyUhCCCRRUEVpQYO1fi4JaxyxIeNwNNvDqcSObssNEDe7lbnwuZ09X7mcaC4u3q/YuU4LbjN0UiefYFI7Iafd+Ks+A3z9PQ8tCkkVd71iQiQJBAND/9YcNByqM6wxZTIfnwHROBy50msqTUYkLS2dW09tHOM3z2+tRXh7LLlrYzMtkptkfZ0j160xTRcQXW73/+ocCQQC3xZ2UelCYJMUNhFHRljyXjHWQGk0btqkW/ejUY/znfjKp+nZ3/EzwHnwQz6Qkn39GEabHxkEvreACE2IkpS9tAkBMH04QOGCJ0PWzc7r6LSDdu6XF99aBPhMOdTyrkOZtEY3RBabuGJ7NXHevwxMkaa6TmmqGGnvvOs1IVLGnjFp1AkEAnF7NoCqX623WMpM134Xb1wRQgKawl/VMWeEBvb+60evDBnm1VpFbkjIOVWupevQwoxmf9XtPuldUNc/ygcYA3QJAEQEzk6VCymCtogjJ0dszJSzIgqueYhH3AhvHUOfk27ifipkytenK2AnTxTQOcb9OwgjaM3iYSVJA1zt8uloj1w=='
) RETURN NVARCHAR2
IS
    v_plain VARCHAR2(4000);
BEGIN
    IF P_CIPHER IS NULL THEN
        RETURN NULL;
    END IF;
    v_plain := SYS.CRYPTO.RSA_DECRYPT(P_CIPHER, KEYPRIVATE);

    RETURN TO_NCHAR(v_plain);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        RETURN NULL;
END;
-- =======================================================================================
-- MÃ HÓA LAI CHO NHẬT KÝ ĐĂNG NHẬP
-- =======================================================================================

-- Tạo Mã Hóa Lai
CREATE OR REPLACE PACKAGE PKG_LOG_SECURITY AS
    PROCEDURE INSERT_LOG_HYBRID(p_userid IN VARCHAR2, p_ip IN VARCHAR2);   
    -- Hàm giải mã lấy lại IP gốc
    FUNCTION DECRYPT_IP_HYBRID(p_ip_enc IN RAW, p_key_enc IN RAW) RETURN VARCHAR2;
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_LOG_SECURITY AS
    FUNCTION GEN_SESSION_KEY RETURN RAW IS
    BEGIN
        RETURN DBMS_CRYPTO.RANDOMBYTES(32);
    END;


    PROCEDURE INSERT_LOG_HYBRID(p_userid IN VARCHAR2, p_ip IN VARCHAR2) IS
        v_session_key RAW(32);
        v_ip_enc      RAW(2000);
        v_key_enc     RAW(2000);
    BEGIN
        v_session_key := GEN_SESSION_KEY();
       
        v_ip_enc := DBMS_CRYPTO.ENCRYPT(
            src => UTL_RAW.CAST_TO_RAW(p_ip),
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_session_key
        );
        v_key_enc := HEXTORAW(PKG_SECURITY.Encrypt_AES(RAWTOHEX(v_session_key)));

        INSERT INTO LOGIN_HISTORY (USERID, LOGIN_TIME, IP_ENCRYPTED, SESSION_KEY_ENC)
        VALUES (p_userid, CURRENT_TIMESTAMP, v_ip_enc, v_key_enc);
        
    EXCEPTION WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Loi Hybrid Encrypt: ' || SQLERRM);
    END;

    -- Hàm giải mã IP
    FUNCTION DECRYPT_IP_HYBRID(p_ip_enc IN RAW, p_key_enc IN RAW) RETURN VARCHAR2 IS
        v_session_key RAW(32);
        v_ip_decrypted RAW(2000);
    BEGIN
        IF p_ip_enc IS NULL OR p_key_enc IS NULL THEN RETURN NULL; END IF;
        v_session_key := HEXTORAW(PKG_SECURITY.Decrypt_AES(RAWTOHEX(p_key_enc)));
        v_ip_decrypted := DBMS_CRYPTO.DECRYPT(
            src => p_ip_enc,
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_session_key
        );
        
        RETURN UTL_RAW.CAST_TO_VARCHAR2(v_ip_decrypted);
    EXCEPTION WHEN OTHERS THEN
        RETURN 'Error-Decrypt';
    END;

END;
/
COMMIT;

-- =======================================================================================
-- INSERT
-- =======================================================================================

-- Phòng ban
INSERT INTO PHONGBAN VALUES ('PB001', N'Công nghệ thông tin');
INSERT INTO PHONGBAN VALUES ('PB002', N'Nhân sự');
INSERT INTO PHONGBAN VALUES ('PB003', N'Kế toán');
INSERT INTO PHONGBAN VALUES ('PB004', N'Marketing');
INSERT INTO PHONGBAN VALUES ('PB005', N'Sản xuất');

-- Tài khoản admin
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U000', 'supadmin', '123', 'admin@company.com', N'Quản Trị Viên Hệ Thống', 'PB001', 'ADMIN', '0900000000', N'Nam');

-- Tài khoản lead va user
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U001', 'phucle', '123', 'phucle@company.com', N'Lê Nguyễn Hồng Phúc', 'PB001', 'LEAD', '0911111111', N'Nam');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U002', 'thanhphan', '123', 'thanhpham@company.com', N'Phạm Tiến Thành', 'PB001', 'USER', '0911111112', N'Nam');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U003', 'lanvo', '123', 'lanvo@company.com', N'Võ Thị Ngọc Lan', 'PB001', 'USER', '0911111113', N'Nữ');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI) 
VALUES ('U010', 'lecu2', '123_raw', 'lecul234@gmail.com', N'Trần Lê Cu', 'PB002', 'USER', '09444444885');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U004', 'mailinh', '1234', 'mailinh@company.com', N'Trần Mai Linh', 'PB002', 'LEAD', '0922222221', N'Nữ');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U005', 'hungle', '1234', 'hungle@company.com', N'Lê Văn Hùng', 'PB002', 'USER', '0922222222', N'Nam');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U006', 'thuaha', '123', 'thuha@company.com', N'Nguyễn Thu Hà', 'PB002', 'USER', '0922222223', N'Nữ');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U007', 'kientran', '123', 'kientran@company.com', N'Trần Trung Kiên', 'PB003', 'LEAD', '0933333331', N'Nam');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U008', 'bichngoc', '123', 'bichngoc@company.com', N'Phạm Bích Ngọc', 'PB003', 'USER', '0933333332', N'Nữ');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U009', 'minhtuan', '123', 'minhtuan@company.com', N'Hoàng Minh Tuấn', 'PB003', 'USER', '0933333333', N'Nam');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U013', 'phuongthao', '123', 'phuongthao@company.com', N'Lê Phương Thảo', 'PB004', 'LEAD', '0944444441', N'Nữ');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U014', 'duykhang', '123', 'duykhang@company.com', N'Ngô Duy Khang', 'PB004', 'USER', '0944444442', N'Nam');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U015', 'yennhi', '123', 'yennhi@company.com', N'Vũ Yến Nhi', 'PB004', 'USER', '0944444443', N'Nữ');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U016', 'prod_lead', '123_raw', 'vanbinh@company.com', N'Đỗ Văn Bình', 'PB005', 'LEAD', '0955555551', N'Nam');
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U017', 'prod_staff1', '123_raw', 'thuthuy@company.com', N'Bùi Thu Thủy', 'PB005', 'USER', '0955555552', N'Nữ');

commit;

-- Nhóm chat
INSERT INTO NHOMCHAT (MANHOM, TENNHOM, LOAI_NHOM, NGAYTAO, TAOBOI) VALUES ('N001', N'Phòng CNTT', 0, SYSDATE, 'U001');
INSERT INTO NHOMCHAT (MANHOM, TENNHOM, LOAI_NHOM, NGAYTAO, TAOBOI) VALUES ('N002', N'Phòng Nhân sự', 0, SYSDATE, 'U001');
INSERT INTO NHOMCHAT (MANHOM, TENNHOM, LOAI_NHOM, NGAYTAO, TAOBOI) VALUES ('N003', N'Phòng Kế toán', 0, SYSDATE, 'U001');
INSERT INTO NHOMCHAT (MANHOM, TENNHOM, LOAI_NHOM, NGAYTAO, TAOBOI) VALUES ('N004', N'Phòng Marketing', 0, SYSDATE, 'U001');
INSERT INTO NHOMCHAT (MANHOM, TENNHOM, LOAI_NHOM, NGAYTAO, TAOBOI) VALUES ('N005', N'Phòng Sản xuất', 0, SYSDATE, 'U001');
INSERT INTO NHOMCHAT (MANHOM, TENNHOM, LOAI_NHOM, NGAYTAO, TAOBOI) VALUES ('GENERAL', N'Kênh chung toàn công ty', 2, SYSDATE, 'U000');
COMMIT;

-- Tin nhắn 
INSERT INTO TINNHAN (MATN, MANHOM, GUIBOI, NOIDUNG, THOIGIAN) VALUES ('TN01', 'N001', 'U001', N'Xin chào mọi người!', SYSDATE-1);
INSERT INTO TINNHAN (MATN, MANHOM, GUIBOI, NOIDUNG, THOIGIAN) VALUES ('TN02', 'N003', 'U008', N'Báo cáo tài chính xong chưa?', SYSDATE);
COMMIT;

-- Thành viên nhóm
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N001', 'U001', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N001', 'U002', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N001', 'U003', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N002', 'U004', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N002', 'U006', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N003', 'U007', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N003', 'U008', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N003', 'U009', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N004', 'U013', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N004', 'U014', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N004', 'U015', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N005', 'U016', 1);
INSERT INTO THANHVIENNHOM (MANHOM, USERID, DUYET) VALUES ('N005', 'U017', 1);
COMMIT;

-- =======================================================================================
-- TRIGGER MÃ HÓA PASS BẰNG AES
-- =======================================================================================

CREATE OR REPLACE TRIGGER TRG_ENCRYPT_TAIKHOAN
BEFORE INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    IF :NEW.PASSWORD IS NOT NULL THEN
        :NEW.PASSWORD := PKG_SECURITY.Encrypt_AES(:NEW.PASSWORD);
    END IF;

END;
/

-- =======================================================================================
-- VPD
-- =======================================================================================

CREATE OR REPLACE CONTEXT CTX_QLCHAT USING PKG_SESSION_CTX;

CREATE OR REPLACE PACKAGE PKG_SESSION_CTX AS
    PROCEDURE SET_USER_ID(p_userid IN VARCHAR2);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_SESSION_CTX AS
    PROCEDURE SET_USER_ID(p_userid IN VARCHAR2) IS
    BEGIN
        DBMS_SESSION.SET_CONTEXT('CTX_QLCHAT', 'USER_ID', p_userid);
    END;
END;
/

CREATE OR REPLACE FUNCTION FUNC_AUTH_NHOMCHAT (
    schema_p IN VARCHAR2,
    table_p  IN VARCHAR2
) RETURN VARCHAR2 AS
    v_userid VARCHAR2(50);
    v_condition VARCHAR2(2000);
BEGIN
    v_userid := SYS_CONTEXT('CTX_QLCHAT', 'USER_ID');
    
    -- Admin thấy hết
    IF v_userid = 'U000' OR v_userid IS NULL THEN
        RETURN '1=1'; 
    END IF;
    v_condition := 'MANHOM IN (SELECT MANHOM FROM NHOM8.THANHVIENNHOM WHERE USERID = ''' || v_userid || ''') OR LOAI_NHOM = 2';
    
    RETURN v_condition;
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY (
        object_schema    => 'NHOM8',
        object_name      => 'NHOMCHAT',      
        policy_name      => 'POLICY_XEM_NHOM',
        function_schema  => 'NHOM8',
        policy_function  => 'FUNC_AUTH_NHOMCHAT', 
        statement_types  => 'SELECT'     
    );
END;
/
--- KIỂM THỬ -- 

EXEC NHOM8.PKG_SESSION_CTX.SET_USER_ID('U002');
SELECT MANHOM,TENNHOM,LOAI_NHOM, TAOBOI
FROM NHOM8.NHOMCHAT

select * from  TAIKHOAN;
select * from tinnhan;
select * from nhomchat;
select * from phongban;
select * from login_history;
COMMIT;

-- =======================================================================================
-- KHÔI PHỤC 
-- =======================================================================================

CREATE TABLE LOG_DELETE_TAIKHOAN (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERID_DELETED VARCHAR2(255),
    USERNAME_DELETED VARCHAR2(50),
    HOTEN_DELETED NVARCHAR2(100),
    MAPHONGBAN_DELETED VARCHAR2(10),
    CHUC_VU_DELETED VARCHAR2(20),
    EMAIL_DELETED VARCHAR2(200),
    THOIGIAN_XOA DATE DEFAULT SYSDATE,
    XOA_BOI VARCHAR2(255)
);
COMMIT;

CREATE OR REPLACE PROCEDURE SP_DELETE_USER_SOFT (
    p_userid_xoa IN VARCHAR2,
    p_user_thuc_hien IN VARCHAR2
)
IS
BEGIN
    INSERT INTO LOG_DELETE_TAIKHOAN (
        USERID_DELETED, USERNAME_DELETED, HOTEN_DELETED, 
        MAPHONGBAN_DELETED, CHUC_VU_DELETED, EMAIL_DELETED, XOA_BOI
    )
    SELECT 
        USERID, USERNAME, HOTEN, 
        MAPHONGBAN, CHUC_VU, EMAIL, p_user_thuc_hien
    FROM TAIKHOAN
    WHERE USERID = p_userid_xoa;
    
    UPDATE TAIKHOAN
    SET TRANGTHAI = 'DELETED', 
        TRUC_TUYEN = 0 
    WHERE USERID = p_userid_xoa;
    
    COMMIT;
END;
/

-- Procedure Khôi phục 
CREATE OR REPLACE PROCEDURE SP_RESTORE_USER (
    p_userid IN VARCHAR2
)
AS
BEGIN
    UPDATE TAIKHOAN 
    SET TRANGTHAI = 'ACTIVE' 
    WHERE USERID = p_userid;

    DELETE FROM LOG_DELETE_TAIKHOAN
    WHERE USERID_DELETED = p_userid;

    COMMIT;
END;
/

-- =======================================================================================
-- AUDIT
-- =======================================================================================

CREATE TABLE log_audit (
    ID_LOG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_NAME VARCHAR2(255),
    ACTION_TIME TIMESTAMP,
    ACTION_TYPE VARCHAR2(10),
    TABLE_NAME VARCHAR2(30),
    OLD_DATA VARCHAR2(2000),
    NEW_DATA VARCHAR2(2000)
);
COMMIT;


-- INSERT TAIKHOAN
CREATE OR REPLACE TRIGGER TG_TK_INS
AFTER INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    INSERT INTO log_audit (USER_NAME, ACTION_TIME, ACTION_TYPE, TABLE_NAME, NEW_DATA)
    VALUES (
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        SYSTIMESTAMP,
        'INSERT',
        'TAIKHOAN',
        'USERID=' || :NEW.USERID || ', USERNAME=' || :NEW.USERNAME || ', HOTEN=' || :NEW.HOTEN 
    );
END;
/

--UPDATE TAIKHOAN
CREATE OR REPLACE TRIGGER TG_TK_UPD
AFTER UPDATE ON TAIKHOAN
FOR EACH ROW
BEGIN
    INSERT INTO log_audit (USER_NAME, ACTION_TIME, ACTION_TYPE, TABLE_NAME, OLD_DATA, NEW_DATA)
    VALUES (
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        SYSTIMESTAMP,
        'UPDATE',
        'TAIKHOAN',
        'OLD: USERID=' || :OLD.USERID || ', USERNAME=' || :OLD.USERNAME || ', HOTEN=' || :OLD.HOTEN,
        'NEW: USERID=' || :NEW.USERID || ', USERNAME=' || :NEW.USERNAME || ', HOTEN=' || :NEW.HOTEN
    );
END;
/

--DELETE TAIKHOAN
CREATE OR REPLACE TRIGGER TG_TK_DEL
AFTER DELETE ON TAIKHOAN
FOR EACH ROW
BEGIN
    INSERT INTO log_audit (USER_NAME, ACTION_TIME, ACTION_TYPE, TABLE_NAME, OLD_DATA)
    VALUES (
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        SYSTIMESTAMP,
        'DELETE',
        'TAIKHOAN',
        'USERID=' || :OLD.USERID || ', USERNAME=' || :OLD.USERNAME || ', HOTEN=' || :OLD.HOTEN
    );
END;
/

--INSERT PHONGBAN
CREATE OR REPLACE TRIGGER TG_PB_INS
AFTER INSERT ON PHONGBAN
FOR EACH ROW
BEGIN
    INSERT INTO log_audit (USER_NAME, ACTION_TIME, ACTION_TYPE, TABLE_NAME, NEW_DATA)
    VALUES (
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        SYSTIMESTAMP,
        'INSERT',
        'PHONGBAN',
        'MAPHONGBAN=' || :NEW.MAPHONGBAN || ', TENPHONGBAN=' || :NEW.TENPHONGBAN
    );
END;
/

--UPDATE PHONGBAN
CREATE OR REPLACE TRIGGER TG_PB_UPD
AFTER UPDATE ON PHONGBAN
FOR EACH ROW
BEGIN
    INSERT INTO log_audit (USER_NAME, ACTION_TIME, ACTION_TYPE, TABLE_NAME, OLD_DATA, NEW_DATA)
    VALUES (
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        SYSTIMESTAMP,
        'UPDATE',
        'PHONGBAN',
        'OLD: MAPHONGBAN=' || :OLD.MAPHONGBAN || ', TENPHONGBAN=' || :OLD.TENPHONGBAN,
        'NEW: MAPHONGBAN=' || :NEW.MAPHONGBAN || ', TENPHONGBAN=' || :NEW.TENPHONGBAN
    );
END;
/


-- Insert
INSERT INTO TAIKHOAN (USERID, USERNAME, PASSWORD, EMAIL, HOTEN, MAPHONGBAN, CHUC_VU, DIENTHOAI, GIOITINH) 
VALUES ('U020', 'phucle1', '123', 'phucle1@company.com', N'Lê Phúc', 'PB001', 'USER', '0922231111', N'Nam');
COMMIT;

-- Update
UPDATE TAIKHOAN
SET HOTEN = N'Phạm Tiến Thành (Đã cập nhật)', DIENTHOAI = '0999999999'
WHERE USERID = 'U020';
COMMIT;

-- Delete
DELETE FROM TAIKHOAN WHERE USERID = 'U020';
COMMIT;

SELECT * FROM LOG_AUDIT ORDER BY ID_LOG;

-- =======================================================================================
-- STANDARD
-- =======================================================================================
ALTER SYSTEM SET AUDIT_TRAIL=DB SCOPE=SPFILE;
SHUTDOWN IMMEDDIATE;
STARTUP;
AUDIT INSERT, UPDATE, DELETE ON taikhoan BY ACCESS;
COMMIT;


-- =======================================================================================
-- OLS 
-- =======================================================================================
BEGIN
   SA_COMPONENTS.CREATE_LEVEL('OLS_TK_POL', 1000, 'PUBLIC', 'Public Level');
   SA_COMPONENTS.CREATE_LEVEL('OLS_TK_POL', 2000, 'CONFIDENTIAL', 'Confidential Level');
END;
/

BEGIN
   SA_LABEL_ADMIN.CREATE_LABEL('OLS_TK_POL', 1000, 'L_PUB');
   SA_LABEL_ADMIN.CREATE_LABEL('OLS_TK_POL', 2000, 'L_CONF');
END;
/


BEGIN
   SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
     policy_name => 'OLS_TK_POL',
     schema_name => 'NHOM8',
     table_name  => 'THONGBAO', 
     table_options => 'READ_CONTROL'
   );
END;
/
BEGIN
   SA_USER_ADMIN.SET_USER_LABELS('OLS_TK_POL', 'HAIDOI', 'L_CONF'); 
   SA_USER_ADMIN.SET_USER_LABELS('OLS_TK_POL', 'GIABAO', 'L_PUB');  
END;
/
