create user nhom8 identified by 123;
grant create session to nhom8;
grant create table to nhom8;
alter user nhom8 quota 100M on users;
GRANT INSERT ANY TABLE TO nhom8;
GRANT UNLIMITED TABLESPACE TO nhom8;
GRANT CREATE SEQUENCE TO nhom8;
GRANT UNLIMITED TABLESPACE TO nhom8;
GRANT EXECUTE ON DBMS_CRYPTO TO nhom8;
GRANT CREATE PROCEDURE TO nhom8;
ALTER USER nhom8 QUOTA UNLIMITED ON USERS;
GRANT CREATE TRIGGER TO nhom8;
GRANT JAVAUSERPRIV TO nhom8;
GRANT JAVASYSPRIV TO nhom8;
GRANT JAVADEBUGPRIV TO nhom8;
--
GRANT CREATE ANY CONTEXT TO NHOM8;
GRANT EXECUTE ON DBMS_RLS TO NHOM8;
GRANT CREATE ROLE TO NHOM8;
COMMIT;

grant execute on CRYPTO to nhom8;
-- PROFILE --- 
CREATE PROFILE PF_SECURE LIMIT
    SESSIONS_PER_USER 5         
    IDLE_TIME 15                 
    CONNECT_TIME 600             
    FAILED_LOGIN_ATTEMPTS 3     
    PASSWORD_LIFE_TIME 90        
    PASSWORD_GRACE_TIME 7        
    PASSWORD_LOCK_TIME 1;        
    

ALTER USER nhom8 PROFILE PF_SECURE;
ALTER USER BAO1 PROFILE PF_SECURE;
ALTER USER HONGPHUC PROFILE PF_SECURE;

---- tao user ----
CREATE USER USER_XEM IDENTIFIED BY 123;
GRANT CREATE SESSION TO USER_XEM;
GRANT SELECT, INSERT ON NHOM8.TAIKHOAN TO USER_XEM;

CREATE USER HONGPHUC IDENTIFIED BY 123;
GRANT CREATE SESSION TO HONGPHUC;
GRANT SELECT, INSERT,UPDATE ON NHOM8.TAIKHOAN TO HONGPHUC;

CREATE USER BAO1 IDENTIFIED BY 123;
GRANT CREATE SESSION TO BAO1;
GRANT SELECT, INSERT ON NHOM8.TAIKHOAN TO BAO1;
-- 1. Tạo Policy
BEGIN
    SA_SYSDBA.CREATE_POLICY(
        policy_name => 'OLS_TK_POL',
        column_name => 'OLS_LABEL_COL'
    );
END;
/
BEGIN
    LBACSYS.CONFIGURE_OLS;
END;
/

BEGIN
    LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
END;
/
ALTER USER lbacsys ACCOUNT UNLOCK IDENTIFIED BY lbacsys;
SELECT VALUE FROM v$option WHERE PARAMETER = 'Oracle Label Security';
COMMIT;

--------
-- ROLL (NHÓM QUYỀN )---
CREATE ROLE admin_role;
GRANT CREATE SESSION,
      CREATE TABLE,
      ALTER ANY TABLE,
      DROP ANY TABLE,
      CREATE USER,
      ALTER USER
TO admin_role;

CREATE ROLE user_role;

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE VIEW
TO user_role;


--- tao tablespace ---
CREATE TABLESPACE TS_USERS
DATAFILE 'TS_USERS_01.dbf' SIZE 100M 
AUTOEXTEND ON
NEXT 10M
MAXSIZE UNLIMITED;
--- USER ---
CREATE USER giabao 
IDENTIFIED BY "123"
DEFAULT TABLESPACE TS_USERS
PROFILE PF_SECURE
QUOTA 50M ON TS_USERS;

GRANT user_role TO giabao;

--- admin --- 
CREATE USER haidoi
IDENTIFIED BY "123"
DEFAULT TABLESPACE TS_USERS
PROFILE PF_SECURE
QUOTA 100M ON TS_USERS;

GRANT admin_role TO haidoi;

--- kiemtra --
SELECT username, default_tablespace, profile, account_status
FROM dba_users
WHERE username IN ('HAIDOI', 'GIABAO');

--- KIEM TRA ---
SELECT grantee, granted_role 
FROM dba_role_privs
WHERE grantee IN ('HAIDOI', 'GIABAO');
--- KIEM TRA QUYEN ROLL ---
SELECT * FROM dba_sys_privs WHERE grantee = 'USER_ROLE';
SELECT * FROM dba_sys_privs WHERE grantee = 'ADMIN_ROLE';


--- FGA ---
BEGIN
  DBMS_FGA.ADD_POLICY(
    object_schema   => 'NHOM8',
    object_name     => 'TAIKHOAN',
    policy_name     => 'AUDIT_XEM_MATKHAU',
    audit_column    => 'PASSWORD, AES_KEY_ENC', -- Cột cần giám sát
    enable          => TRUE,
    statement_types => 'SELECT, UPDATE'
  );
END;
/
 SELECT * FROM DBA_FGA_AUDIT_TRAIL;
--- vpd --- 
